### PR TITLE
Fixing markdown errors in README.md

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by litong01** [comment]
is this a new project? what does it do? Thanks.

**Comment by ryjones** [comment]
> is this a new project? what does it do? Thanks.

It looks like the change is to add a space in the README.md to fix formatting,

**Comment by kshithijiyer** [comment]
And a # as well.

**Comment by ryjones** [comment]
@kshithijiyer you will need to fix your DCO and do a force push to your local branch

https://wiki.hyperledger.org/display/BESU/How+to+Contribute#HowtoContribute-HowtoworkwithDCO

**Comment by yeasy** [comment]
Let's fix the check failure.

**Comment by kshithijiyer** [comment]
Done

**Review by yeasy — APPROVED** [review]
Nice catch, thanks!

**Pull request merged**
